
services:
  db:
    image: mysql:8.0
    container_name: crate_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crate_db
      MYSQL_USER: crate_user
      MYSQL_PASSWORD: crate_pass
    ports:
      - "3307:3306" # host:container
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  mysql_data:
